[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
module Issue144 =
  struct
    type t = Ojs.t
    let rec t_of_js : Ojs.t -> t = fun (x2 : Ojs.t) -> x2
    and t_to_js : t -> Ojs.t = fun (x1 : Ojs.t) -> x1
    let (f : t -> args:int -> int) =
      fun (x3 : t) ->
        fun ~args:(x4 : int) ->
          Ojs.int_of_js
            (Ojs.apply (Ojs.call (t_to_js x3) "f" [||])
               [|(Ojs.int_to_js x4)|])
  end
