module Issue116 =
  struct
    type t
    type s = int[@@js ]
    [@@@ocaml.warning "-7-32-39"]
    let rec (s_of_js : Ojs.t -> s) = Ojs.int_of_js
    and (s_to_js : s -> Ojs.t) = Ojs.int_to_js
    module M :
      sig
        type t
        type s[@@js ]
        [@@@ocaml.warning "-7-32-39"]
        val s_of_js : Ojs.t -> s
        val s_to_js : s -> Ojs.t
      end =
      ((struct
          [@@@js.dummy "!! This code has been generated by gen_js_api !!"]
          [@@@ocaml.warning "-7-32-39"]
          type t = Ojs.t
          let rec (t_of_js : Ojs.t -> t) = fun x4 -> x4
          and (t_to_js : t -> Ojs.t) = fun x3 -> x3
          type s = Ojs.t
          let rec (s_of_js : Ojs.t -> s) = fun x6 -> x6
          and (s_to_js : s -> Ojs.t) = fun x5 -> x5
        end)[@merlin.hide ]) 
  end
module Issue117 :
  sig
    module T :
    ((sig
        val log : 'a -> unit[@@js.global ]
        val log2 : 'a -> 'b -> unit[@@js.global "jsLog2"]
      end)[@js.scope "console"])
  end =
  ((struct
      [@@@js.dummy "!! This code has been generated by gen_js_api !!"]
      [@@@ocaml.warning "-7-32-39"]
      module T =
        struct
          let (log : 'a -> unit) =
            fun x7 ->
              ignore
                (Ojs.call (Ojs.get Ojs.global "console") "log"
                   [|(Obj.magic x7)|])
          let (log2 : 'a -> 'b -> unit) =
            fun x8 ->
              fun x9 ->
                ignore
                  (Ojs.call (Ojs.get Ojs.global "console") "jsLog2"
                     [|(Obj.magic x8);(Obj.magic x9)|])
        end
    end)[@merlin.hide ]) 
