[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
module rec
  Foo:sig
        type t = private Ojs.t
        val t_of_js : Ojs.t -> t
        val t_to_js : t -> Ojs.t
        val create : string -> t
        val describe : t -> string
        val to_bar : t -> Bar.t
      end =
  struct
    type t = Ojs.t
    let rec t_of_js : Ojs.t -> t = fun (x2 : Ojs.t) -> x2
    and t_to_js : t -> Ojs.t = fun (x1 : Ojs.t) -> x1
    let (create : string -> t) =
      fun (x3 : string) ->
        t_of_js
          (Ojs.new_obj (Ojs.get_prop_ascii Ojs.global "Foo")
             [|(Ojs.string_to_js x3)|])
    let (describe : t -> string) =
      fun (x4 : t) ->
        Ojs.string_of_js (Ojs.call (t_to_js x4) "describe" [||])
    let (to_bar : t -> Bar.t) =
      fun (x5 : t) -> Bar.t_of_js (Ojs.call (t_to_js x5) "toBar" [||])
  end
 and
  Bar:sig
        type t = private Ojs.t
        val t_of_js : Ojs.t -> t
        val t_to_js : t -> Ojs.t
        val create : string -> t
        val describe : t -> string
        val to_foo : t -> Foo.t
      end =
  struct
    type t = Ojs.t
    let rec t_of_js : Ojs.t -> t = fun (x7 : Ojs.t) -> x7
    and t_to_js : t -> Ojs.t = fun (x6 : Ojs.t) -> x6
    let (create : string -> t) =
      fun (x8 : string) ->
        t_of_js
          (Ojs.new_obj (Ojs.get_prop_ascii Ojs.global "Bar")
             [|(Ojs.string_to_js x8)|])
    let (describe : t -> string) =
      fun (x9 : t) ->
        Ojs.string_of_js (Ojs.call (t_to_js x9) "describe" [||])
    let (to_foo : t -> Foo.t) =
      fun (x10 : t) -> Foo.t_of_js (Ojs.call (t_to_js x10) "toFoo" [||])
  end
