language: c
sudo: required
before_install:
  - nvm install 12
  - nvm use 12
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - PINS='ojs:.'
  matrix:
  - OCAML_VERSION=4.08 PACKAGE=gen_js_api
  - OCAML_VERSION=4.09 PACKAGE=gen_js_api
  - OCAML_VERSION=4.10 PACKAGE=gen_js_api
os:
  - linux
