include $(shell ocamlc -where)/Makefile.config

OCAMLFLAGS = -w +A-4-41-45 -warn-error +8
OCAMLC = ocamlc $(OCAMLFLAGS)
OJSDIR = $(ROOT)
GENJSAPI= $(ROOT)/gen_js_api$(EXE)
JSOO = js_of_ocaml --pretty --disable genprim
