[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
type t = Ojs.t
let rec (t_of_js : Ojs.t -> t) = fun x2 -> x2
and (t_to_js : t -> Ojs.t) = fun x1 -> x1
let (alloc : int -> t) =
  fun x3 ->
    t_of_js
      (Ojs.call (Ojs.get Ojs.global "Buffer") "alloc" [|(Ojs.int_to_js x3)|])
let (from : string -> t) =
  fun x4 ->
    t_of_js
      (Ojs.call (Ojs.get Ojs.global "Buffer") "from"
         [|(Ojs.string_to_js x4)|])
let (concat : t list -> t) =
  fun x5 ->
    t_of_js
      (Ojs.call (Ojs.get Ojs.global "Buffer") "concat"
         [|(Ojs.list_to_js t_to_js x5)|])
let (length : t -> int) =
  fun x7 -> Ojs.int_of_js (Ojs.get (t_to_js x7) "length")
let (get : t -> int -> int option) =
  fun x8 ->
    fun x9 -> Ojs.option_of_js Ojs.int_of_js (Ojs.array_get (t_to_js x8) x9)
let (set : t -> int -> int -> unit) =
  fun x11 ->
    fun x12 -> fun x13 -> Ojs.array_set (t_to_js x11) x12 (Ojs.int_to_js x13)
let (write : t -> string -> int) =
  fun x15 ->
    fun x14 ->
      Ojs.int_of_js
        (Ojs.call (t_to_js x15) "write" [|(Ojs.string_to_js x14)|])
let (slice : t -> int -> int -> t) =
  fun x18 ->
    fun x16 ->
      fun x17 ->
        t_of_js
          (Ojs.call (t_to_js x18) "slice"
             [|(Ojs.int_to_js x16);(Ojs.int_to_js x17)|])
let (to_string : t -> string) =
  fun x19 -> Ojs.string_of_js (Ojs.call (t_to_js x19) "toString" [||])
let (copy : t -> dst:t -> start:int -> dst_start:int -> dst_end:int -> int) =
  fun x24 ->
    fun ~dst:x20 ->
      fun ~start:x21 ->
        fun ~dst_start:x22 ->
          fun ~dst_end:x23 ->
            Ojs.int_of_js
              (Ojs.call (t_to_js x24) "copy"
                 [|(t_to_js x20);(Ojs.int_to_js x21);(Ojs.int_to_js x22);(
                   Ojs.int_to_js x23)|])
