[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
let (log : 'a -> unit) =
  fun (x1 : 'a) ->
    ignore
      (Jsoo_runtime.Js.meth_call
         (Jsoo_runtime.Js.get (Jsoo_runtime.Js.pure_js_expr "globalThis")
            (Ojs.string_to_js "console")) "log" [|(Obj.magic x1)|])
let (error : 'a -> unit) =
  fun (x2 : 'a) ->
    ignore
      (Jsoo_runtime.Js.meth_call
         (Jsoo_runtime.Js.get (Jsoo_runtime.Js.pure_js_expr "globalThis")
            (Ojs.string_to_js "console")) "error" [|(Obj.magic x2)|])
module T =
  struct
    let (log : (module Ojs.T with type t = 'a) -> 'a -> unit) =
      fun (type a) ->
        fun ((module A)  : (module Ojs.T with type t = a)) ->
          fun (x3 : a) ->
            ignore
              (Jsoo_runtime.Js.meth_call
                 (Jsoo_runtime.Js.get
                    (Jsoo_runtime.Js.pure_js_expr "globalThis")
                    (Ojs.string_to_js "console")) "log" [|(A.t_to_js x3)|])
    let (error : (module Ojs.T with type t = 'a) -> 'a -> unit) =
      fun (type a) ->
        fun ((module A)  : (module Ojs.T with type t = a)) ->
          fun (x4 : a) ->
            ignore
              (Jsoo_runtime.Js.meth_call
                 (Jsoo_runtime.Js.get
                    (Jsoo_runtime.Js.pure_js_expr "globalThis")
                    (Ojs.string_to_js "console")) "error" [|(A.t_to_js x4)|])
  end
