[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
let (path : Ojs.t) =
  Ojs.get (Ojs.get Ojs.global "__LIB__NODE__IMPORTS") "path"
let (fs_promises : Ojs.t) =
  Ojs.get (Ojs.get Ojs.global "__LIB__NODE__IMPORTS") "fsPromises"
