[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
type t = Ojs.t
let rec t_of_js : Ojs.t -> t = fun (x2 : Ojs.t) -> x2
and t_to_js : t -> Ojs.t = fun (x1 : Ojs.t) -> x1
let (toString : t -> ?radix:int -> unit -> float) =
  fun (x6 : t) ->
    fun ?radix:(x3 : int option) ->
      fun () ->
        Ojs.float_of_js
          (let x7 = t_to_js x6 in
           Jsoo_runtime.Js.meth_call
             (Jsoo_runtime.Js.get x7 (Obj.magic "toString")) "apply"
             [|x7;((let x4 =
                      Jsoo_runtime.Js.new_obj
                        (Jsoo_runtime.Js.get
                           (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
                           (Obj.magic "Array")) [||] in
                    (match x3 with
                     | Some x5 ->
                         ignore
                           (Jsoo_runtime.Js.meth_call x4 "push"
                              [|(Ojs.int_to_js x5)|])
                     | None -> ());
                    x4))|])
let (toFixed : t -> ?fractionDigits:int -> unit -> float) =
  fun (x11 : t) ->
    fun ?fractionDigits:(x8 : int option) ->
      fun () ->
        Ojs.float_of_js
          (let x12 = t_to_js x11 in
           Jsoo_runtime.Js.meth_call
             (Jsoo_runtime.Js.get x12 (Obj.magic "toFixed")) "apply"
             [|x12;((let x9 =
                       Jsoo_runtime.Js.new_obj
                         (Jsoo_runtime.Js.get
                            (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
                            (Obj.magic "Array")) [||] in
                     (match x8 with
                      | Some x10 ->
                          ignore
                            (Jsoo_runtime.Js.meth_call x9 "push"
                               [|(Ojs.int_to_js x10)|])
                      | None -> ());
                     x9))|])
let (toExponential : t -> ?fractionDigits:int -> unit -> float) =
  fun (x16 : t) ->
    fun ?fractionDigits:(x13 : int option) ->
      fun () ->
        Ojs.float_of_js
          (let x17 = t_to_js x16 in
           Jsoo_runtime.Js.meth_call
             (Jsoo_runtime.Js.get x17 (Obj.magic "toExponential")) "apply"
             [|x17;((let x14 =
                       Jsoo_runtime.Js.new_obj
                         (Jsoo_runtime.Js.get
                            (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
                            (Obj.magic "Array")) [||] in
                     (match x13 with
                      | Some x15 ->
                          ignore
                            (Jsoo_runtime.Js.meth_call x14 "push"
                               [|(Ojs.int_to_js x15)|])
                      | None -> ());
                     x14))|])
let (toPrecision : t -> ?precision:int -> unit -> float) =
  fun (x21 : t) ->
    fun ?precision:(x18 : int option) ->
      fun () ->
        Ojs.float_of_js
          (let x22 = t_to_js x21 in
           Jsoo_runtime.Js.meth_call
             (Jsoo_runtime.Js.get x22 (Obj.magic "toPrecision")) "apply"
             [|x22;((let x19 =
                       Jsoo_runtime.Js.new_obj
                         (Jsoo_runtime.Js.get
                            (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
                            (Obj.magic "Array")) [||] in
                     (match x18 with
                      | Some x20 ->
                          ignore
                            (Jsoo_runtime.Js.meth_call x19 "push"
                               [|(Ojs.int_to_js x20)|])
                      | None -> ());
                     x19))|])
let (valueOf : t -> float) =
  fun (x23 : t) ->
    Ojs.float_of_js (Jsoo_runtime.Js.meth_call (t_to_js x23) "valueOf" [||])
module Scoped =
  struct
    let (create : 'any -> t) =
      fun (x24 : 'any) ->
        t_of_js
          (Jsoo_runtime.Js.new_obj
             (Jsoo_runtime.Js.get
                (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
                (Obj.magic "Number")) [|(Obj.magic x24)|])
    let (invoke : 'any -> float) =
      fun (x25 : 'any) ->
        Ojs.float_of_js
          (Jsoo_runtime.Js.fun_call
             (Jsoo_runtime.Js.get
                (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
                (Obj.magic "Number")) [|(Obj.magic x25)|])
    let (min_value : float) =
      Ojs.float_of_js
        (Jsoo_runtime.Js.get
           (Jsoo_runtime.Js.get
              (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
              (Obj.magic "Number")) (Obj.magic "MIN_VALUE"))
    let (max_value : float) =
      Ojs.float_of_js
        (Jsoo_runtime.Js.get
           (Jsoo_runtime.Js.get
              (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
              (Obj.magic "Number")) (Obj.magic "MAX_VALUE"))
    let (nan : float) =
      Ojs.float_of_js
        (Jsoo_runtime.Js.get
           (Jsoo_runtime.Js.get
              (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
              (Obj.magic "Number")) (Obj.magic "NaN"))
    let (negative_infinity : float) =
      Ojs.float_of_js
        (Jsoo_runtime.Js.get
           (Jsoo_runtime.Js.get
              (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
              (Obj.magic "Number")) (Obj.magic "NEGATIVE_INFINITY"))
    let (positive_infinity : float) =
      Ojs.float_of_js
        (Jsoo_runtime.Js.get
           (Jsoo_runtime.Js.get
              (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
              (Obj.magic "Number")) (Obj.magic "POSITIVE_INFINITY"))
  end
module Static =
  struct
    type number = t
    let rec number_of_js : Ojs.t -> number = fun (x27 : Ojs.t) -> t_of_js x27
    and number_to_js : number -> Ojs.t = fun (x26 : t) -> t_to_js x26
    type t = Ojs.t
    let rec t_of_js : Ojs.t -> t = fun (x29 : Ojs.t) -> x29
    and t_to_js : t -> Ojs.t = fun (x28 : Ojs.t) -> x28
    let (create : t -> 'any -> number) =
      fun (x31 : t) ->
        fun (x30 : 'any) ->
          number_of_js
            (Jsoo_runtime.Js.new_obj (t_to_js x31) [|(Obj.magic x30)|])
    let (apply : t -> 'any -> float) =
      fun (x33 : t) ->
        fun (x32 : 'any) ->
          Ojs.float_of_js
            (Jsoo_runtime.Js.fun_call (t_to_js x33) [|(Obj.magic x32)|])
    let (min_value : t -> float) =
      fun (x34 : t) ->
        Ojs.float_of_js
          (Jsoo_runtime.Js.get (t_to_js x34) (Obj.magic "MIN_VALUE"))
    let (max_value : t -> float) =
      fun (x35 : t) ->
        Ojs.float_of_js
          (Jsoo_runtime.Js.get (t_to_js x35) (Obj.magic "MAX_VALUE"))
    let (nan : t -> float) =
      fun (x36 : t) ->
        Ojs.float_of_js (Jsoo_runtime.Js.get (t_to_js x36) (Obj.magic "NaN"))
    let (negative_infinity : t -> float) =
      fun (x37 : t) ->
        Ojs.float_of_js
          (Jsoo_runtime.Js.get (t_to_js x37) (Obj.magic "NEGATIVE_INFINITY"))
    let (positive_infinity : t -> float) =
      fun (x38 : t) ->
        Ojs.float_of_js
          (Jsoo_runtime.Js.get (t_to_js x38) (Obj.magic "POSITIVE_INFINITY"))
  end
let (number : Static.t) =
  Static.t_of_js
    (Jsoo_runtime.Js.get (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
       (Obj.magic "Number"))
