[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
type t = Ojs.t
let rec t_of_js : Ojs.t -> t = fun (x2 : Ojs.t) -> x2
and t_to_js : t -> Ojs.t = fun (x1 : Ojs.t) -> x1
let (values : 'a -> Ojs.t array) =
  fun (x3 : 'a) ->
    Ojs.array_of_js (fun (x4 : Ojs.t) -> x4)
      (Jsoo_runtime.Js.meth_call
         (Jsoo_runtime.Js.get
            (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
            (Obj.magic "Object")) "values" [|(Obj.magic x3)|])
