[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
let (sep : string) =
  Ojs.string_of_js (Jsoo_runtime.Js.get Imports.path (Obj.magic "sep"))
let (dirname : string -> string) =
  fun (x1 : string) ->
    Ojs.string_of_js
      (Jsoo_runtime.Js.meth_call Imports.path "dirname"
         [|(Ojs.string_to_js x1)|])
let (extname : string -> string) =
  fun (x2 : string) ->
    Ojs.string_of_js
      (Jsoo_runtime.Js.meth_call Imports.path "extname"
         [|(Ojs.string_to_js x2)|])
let (is_absolute : string -> bool) =
  fun (x3 : string) ->
    Ojs.bool_of_js
      (Jsoo_runtime.Js.meth_call Imports.path "isAbsolute"
         [|(Ojs.string_to_js x3)|])
let (join : string list -> string) =
  fun (x4 : string list) ->
    Ojs.string_of_js
      (let x7 = Imports.path in
       Jsoo_runtime.Js.meth_call (Jsoo_runtime.Js.get x7 (Obj.magic "join"))
         "apply"
         [|x7;((let x5 =
                  Jsoo_runtime.Js.new_obj
                    (Jsoo_runtime.Js.get
                       (Jsoo_runtime.Js.pure_js_expr "joo_global_object")
                       (Obj.magic "Array")) [||] in
                List.iter
                  (fun (x6 : string) ->
                     ignore
                       (Jsoo_runtime.Js.meth_call x5 "push"
                          [|(Ojs.string_to_js x6)|])) x4;
                x5))|])
let (normalize : string -> string) =
  fun (x8 : string) ->
    Ojs.string_of_js
      (Jsoo_runtime.Js.meth_call Imports.path "normalize"
         [|(Ojs.string_to_js x8)|])
type parse_result =
  {
  dir: string ;
  root: string ;
  base: string ;
  name: string ;
  ext: string }
let rec parse_result_of_js : Ojs.t -> parse_result =
  fun (x10 : Ojs.t) ->
    {
      dir = (Ojs.string_of_js (Jsoo_runtime.Js.get x10 (Obj.magic "dir")));
      root = (Ojs.string_of_js (Jsoo_runtime.Js.get x10 (Obj.magic "root")));
      base = (Ojs.string_of_js (Jsoo_runtime.Js.get x10 (Obj.magic "base")));
      name = (Ojs.string_of_js (Jsoo_runtime.Js.get x10 (Obj.magic "name")));
      ext = (Ojs.string_of_js (Jsoo_runtime.Js.get x10 (Obj.magic "ext")))
    }
and parse_result_to_js : parse_result -> Ojs.t =
  fun (x9 : parse_result) ->
    Jsoo_runtime.Js.obj
      [|("dir", (Ojs.string_to_js x9.dir));("root",
                                             (Ojs.string_to_js x9.root));
        ("base", (Ojs.string_to_js x9.base));("name",
                                               (Ojs.string_to_js x9.name));
        ("ext", (Ojs.string_to_js x9.ext))|]
let (parse : string -> parse_result) =
  fun (x11 : string) ->
    parse_result_of_js
      (Jsoo_runtime.Js.meth_call Imports.path "parse"
         [|(Ojs.string_to_js x11)|])
