[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
let (env : string Container.StringMap.t) =
  Container.StringMap.t_of_js Ojs.string_of_js
    (Ojs.get_prop_ascii (Ojs.get_prop_ascii Ojs.global "process") "env")
let (version : string option) =
  Ojs.option_of_js Ojs.string_of_js
    (Ojs.get_prop_ascii (Ojs.get_prop_ascii Ojs.global "process") "version")
