name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # disabled for now:
          # - macos-latest
          # - windows-latest
        node-version:
          - 14.x
        ocaml-compiler:
          - 4.14.x
          - 4.12.x
          - 4.11.x
          - 4.10.x
          - 4.09.x
          - 4.08.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-pin: false
          dune-cache: ${{ matrix.os != 'windows-latest' }}

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- make

      - run: opam exec -- make test
        continue-on-error: ${{ runner.os == 'Windows' }}
